# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "http://ergz.github.io/CSUEB-Big-Data" # the subpath of your site, e.g. /blog/
github_username: ERGZ
# Build settings
markdown: redcarpet
