# Site settings
title: CSUEB Data Science Group 
description: Data Science at Cal State East Bay
email: data.science.CSUEB@gmail.com
baseurl: "/CSUEB-Data-Science" # the subpath of your site, e.g. /blog/
github_username: ERGZ
# Build settings
markdown: redcarpet
