# Site settings
title: CSUEB Data Science Group 
description: Big Data and Data Science at Cal State East Bay
email: data.science.CSUEB@gmail.com
baseurl: "/CSUEB-Big-Data" # the subpath of your site, e.g. /blog/
github_username: ERGZ
# Build settings
markdown: redcarpet
